"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .createburger import *
from .createorder import *
from .deleteburger import *
from .listburgers import *
from .listorders import *
from .readburger import *
from .readorder import *
from .updateburger import *
from .updateorder import *

__all__ = ["CreateBurgerResponse","CreateOrderResponse","DeleteBurgerRequest","DeleteBurgerResponse","ListBurgersResponse","ListOrdersResponse","ReadBurgerRequest","ReadBurgerResponse","ReadOrderRequest","ReadOrderResponse","UpdateBurgerRequest","UpdateBurgerResponse","UpdateOrderRequest","UpdateOrderResponse"]
