"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import responsemessage as shared_responsemessage
from typing import Optional



@dataclasses.dataclass
class DeleteBurgerRequest:
    burger_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'burger_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class DeleteBurgerResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    response_message: Optional[shared_responsemessage.ResponseMessage] = dataclasses.field(default=None)
    r"""Burger deleted"""
    

