"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import burgeroutput as shared_burgeroutput
from typing import Optional



@dataclasses.dataclass
class ListBurgersResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    burger_outputs: Optional[list[shared_burgeroutput.BurgerOutput]] = dataclasses.field(default=None)
    r"""Successful Response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

