"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .burgerupdate import BurgerUpdate, BurgerUpdateTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateBurgerRequestTypedDict(TypedDict):
    burger_update: BurgerUpdateTypedDict
    burger_id: int


class UpdateBurgerRequest(BaseModel):
    burger_update: Annotated[
        BurgerUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    burger_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
